### ISSUE TITLE
Failed to create a Decompressor() on MAUI Android

### ISSUE THREAD

**Issue by zh4ui** [oleg-st/ZstdSharp#14]
Hi,

I was trying to use ZstdSharp (ver 0.6.6) in a MAUI project targeting Android.
The building was fine, but when I ran it, exception raised when constructing a Decompressor.

The exception was at line <https://github.com/oleg-st/ZstdSharp/blob/master/src/ZstdSharp/Unsafe/ZstdCompress.cs#L2725> with the following information

```
System.ArrayTypeMismatchException
  Message=Attempted to access an element as a type incompatible with the array.
```

**Comment by oleg-st** [comment]
Looks like a problem with Mono which doesn't support nested arrays with function pointers.

A code with the same exception:
```csharp
unsafe class Program
{
    public static delegate* managed<int>[][] Functions = {
        new delegate* managed<int>[]
        {
            &Function,
        },
    };

    public static int Function() => 42;
}
```

**Comment by zh4ui** [comment]
Just wanted to ask is there a way around it with Mono?

**Comment by oleg-st** [comment]
I will make a workaround for this.

**Comment by oleg-st** [comment]
Fixed in 0.6.7

**Comment by oleg-st** [comment]
@zh4ui Could you check it?

**Comment by zh4ui** [comment]
> Sure, I will check it tomorrow

Thanks for the update!
With 0.6.7, I confirm it's now okay to do dictionary-based decompression on MAUI for Android.
