### ISSUE TITLE
Dispose inner streams

### ISSUE THREAD

**Issue by bastianeicher** [oleg-st/ZstdSharp#15]
Awesome library, thanks! Using this happily in [0install](https://github.com/0install/0install-dotnet).

Many Streams that wrap other Streams dispose the underlying Streams when they are disposed. Often they provide an optional bool parameter to control this behaviour. Example: .NET‘s built-in [GZipStream](https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO.Compression/src/System/IO/Compression/GZipStream.cs).

Could you perhaps add similar behaviour to `CompressionStream` and `DecompressionStream`?

**Comment by oleg-st** [comment]
Thank you for your interest!

Added `preserveStream` argument to `CompressionStream` and `DecompressionStream` in 22cee6aa57f99470e81664c301fe676790b073fb

**Comment by bastianeicher** [comment]
Thanks!
