### ISSUE TITLE
Can't compile with .NET compile tool chain for UWP app

### ISSUE THREAD

**Issue by johnnylee194** [oleg-st/ZstdSharp#17]
I've had [this issue](https://jira.mongodb.org/browse/CSHARP-4553) when building an UWP app, in short:

- I have this UWP app to use MongoDB C# Driver
- Building error comes from MongoDB C# Driver
- [Dmitry Lukyanov](https://jira.mongodb.org/secure/ViewProfile.jspa?name=dmitry.lukyanov%40mongodb.com) from MongoDB C# Driver project told me this error comes from zstd compression impl

So I'm opening this issue here to see whether this can be fixed

**Comment by oleg-st** [comment]
I can fix warnings "ILTransform : warning ILT0027: Invalid IL detected", but "error : Internal compiler error: Object reference not set to an instance of an object" still remains and I don't understand the reason for it.

**Comment by johnnylee194** [comment]
Thanks for the response, I'll see whether I can get some help from MSDN and will get back to here for any positive feedback

**Comment by oleg-st** [comment]
Released 0.7.0 without these warning but it still does not compile with .NET Native

**Comment by johnnylee194** [comment]
Gotcha, thanks

**Comment by oleg-st** [comment]
@johnnylee194 

I think it's fixed in 0.7.3

You may need `<Use64BitCompiler>true</Use64BitCompiler>` or `<SingleThreadNUTC>true</SingleThreadNUTC>` 
 in the project file to avoid out of memory problems in compiler.

**Comment by johnnylee194** [comment]
Gotcha.  Thanks for the fix.
