### ISSUE TITLE
Port fix for zstd block splitter bug

### ISSUE THREAD

**Issue by JamesKovacs** [oleg-st/ZstdSharp#18]
Zstd recently released v1.5.5 to fix a [bug in the block splitter](https://github.com/facebook/zstd/pull/3517/files). Given that ZstdSharp recently ported v1.5.4 and the block splitter bug appears to be fundamentally an algorithm logic bug, ZstdSharp is likely affected by this bug too.

**Comment by oleg-st** [comment]
I'll port zstd v1.5.5
