### ISSUE TITLE
"Premature end of stream" exception when decompressing re-compressed output

### ISSUE THREAD

**Issue by PiMoNFeeD** [oleg-st/ZstdSharp#19]
I was working on a modding tool for a game that uses ZStandard, the tool is capable of decompressing (exporting) and recompressing (importing) files compressed with zstd, it turns out that every version of ZstdSharp after 0.6.1 is unable to decompress back the buffer it has just compressed, throwing the aforementioned exception.

[Example of decompressing](https://github.com/ptasev/Ego-Engine-Modding/blob/master/src/EgoEngineLibrary/Archive/Erp/ErpFragment.cs#L102-L149)
[Example of compressing](https://github.com/ptasev/Ego-Engine-Modding/blob/master/src/EgoEngineLibrary/Archive/Erp/ErpFragment.cs#L173-L179)

0.6.2 introduced a new argument to `DecompressionStream` called `checkEndOfStream`, and setting that to `false` doesn't give an exception, but the files end up being corrupted (in my case that is textures, they appear cut off at the bottom), 0.6.1 does not give any exception and does not corrupt files, either

What I do is, I open the original file from the game, it decompresses fine, then I re-import the same file, it compresses with no errors, but gives the exception when trying to decompress the same compressed buffer it just produced, and loading it in-game looks broken by the end of the file

**Comment by oleg-st** [comment]
You can try to add Dispose / Close to finalize the stream data:

```csharp
using (var bufferWriter = new ArrayPoolBufferWriter<byte>())
{
    using (var zss = new CompressionStream(bufferWriter.AsStream(), ZstdSharp.Unsafe.Methods.ZSTD_defaultCLevel()))
    {
        zss.Write(data, 0, data.Length);
        zss.Flush();
    }
    _data = bufferWriter.WrittenSpan.ToArray();
}
```

**Comment by PiMoNFeeD** [comment]
That appears to have fixed the issue, thanks!
