### ISSUE TITLE
Example needed: TrainFromBufferFastCover

### ISSUE THREAD

**Issue by minimalisticMe** [oleg-st/ZstdSharp#27]
Hi,

after the recent update there is a new function `ZstdSharp.DictBuilder.TrainFromBufferFastCover`, which I think enriches this library massively and makes `zstd` perfect for `.NET` usage.
I want to try and train a custom compression dictionary but have trouble getting results.

Here is my code roughly minimized.
First I collect a list of `byte[]` by reading all files (`json` files) and adding them to a list
```
private static List<byte[]> TestData()
{
    var testData = TestDataList(); // list of paths to json-files

    var testDataList = new List<byte[]>();
    foreach (var item in testData)
    {
        var content = File.ReadAllBytes(item);
        testDataList.Add(content);
    }

    return testDataList;
}
``` 

After that I want to train them by calling
```
var testData = TestData();
var bytes = ZstdSharp.DictBuilder.TrainFromBufferFastCover(testData, 5);
```
and write the result to a file for future use.

However calling `ZstdSharp.DictBuilder.TrainFromBufferFastCover` results in the following error and I don't know how to handle this correctly:
```
ZstdSharp.ZstdException : Src size is incorrect

    ThrowHelper.ThrowException(UIntPtr returnValue, String message)
    ThrowHelper.EnsureZdictSuccess(UIntPtr returnValue)
    DictBuilder.TrainFromBufferFastCover(IEnumerable`1 samples, ZDICT_fastCover_params_t params, Int32 dictCapacity)
    DictBuilder.TrainFromBufferFastCover(IEnumerable`1 samples, Int32 level, Int32 dictCapacity)
    TrainZstdDictionary.TrainDictionary() line 20
    RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
    MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

How do I train a custom dictionary on my own files correctly?

**Comment by oleg-st** [comment]
You may not have enough samples to train, try giving more

**Comment by minimalisticMe** [comment]
I apologize the late answer, it took me some time to procure some more test data.
Now with >12.000 json-files it is qorking just fine :)

**Comment by Mrgaton** [comment]
How much did the compression improved with a trained dictionary?

**Comment by oleg-st** [comment]
https://github.com/facebook/zstd?tab=readme-ov-file#the-case-for-small-data-compression

**Comment by Mrgaton** [comment]
One question, if i compress data with my custom trained dictionary i could then decompress it without loading my dictionary?

**Comment by oleg-st** [comment]
No
