### ISSUE TITLE
Unity 2022.3.19，Cannot resolve symbol 'Shared'

### ISSUE THREAD

**Issue by vinsonzou** [oleg-st/ZstdSharp#34]
IL2CPP
.Net Fromework

```
outputBuffer = ArrayPool<byte>.Shared.Rent(outputBufferSize);
```

Unity Console error output
```
error CS0117: 'ArrayPool<byte>' does not contain a definition for 'Shared'
```

**Comment by oleg-st** [comment]
`ArrayPool<byte>` is contained in [System.Buffers](https://www.nuget.org/packages/System.Buffers) package

**Comment by vinsonzou** [comment]
> `ArrayPool<byte>` is contained in [System.Buffers](https://www.nuget.org/packages/System.Buffers) package

.Net Fromework not support ArrayPool<byte>.Shared

**Comment by oleg-st** [comment]
You need to use the  [System.Buffers](https://www.nuget.org/packages/System.Buffers) nuget package to add `ArrayPool.Shared` to the .NET Framework
