### ISSUE TITLE
Frame requires too much memory for decoding (+ fix)

### ISSUE THREAD

**Issue by KoalaBear84** [oleg-st/ZstdSharp#37]
I've had some issues with decompression a single file, other went fine.

My fix was the following:

```csharp
using FileStream fileStreamInput = File.OpenRead("TheInputPath");
using FileStream fileStreamOutput = File.OpenWrite("TheOutputPath");

using var decompressionStream = new DecompressionStream(fileStreamInput);
// This is the fix
decompressionStream.SetParameter(ZstdSharp.Unsafe.ZSTD_dParameter.ZSTD_d_windowLogMax, 31);
decompressionStream.CopyTo(fileStreamOutput);
```

Took the 31 from this `ZSTD_WINDOWLOG_MAX_64`:
https://github.com/facebook/zstd/blob/v1.4.5/lib/zstd.h#L1049

I have no idea what it all means, but I hope it helps someone stuck with the same issue 😃

**Comment by KoalaBear84** [comment]
Cross posted solution to other lib:
https://github.com/skbkontur/ZstdNet/issues/32

**Comment by oleg-st** [comment]
I think this works as it should. See https://facebook.github.io/zstd/zstd_manual.html#Chapter6 for a description of the ZSTD_d_windowLogMax parameter.

**Comment by KoalaBear84** [comment]
I don't say that anything is wrong 😅 Only issue it wasn't working and I had no idea, found a solution and wanted to let it know for others 😇

Ahh, powers of 2, that makes sense why it's only 31 and not the real amount bytes. 👍

**Comment by oleg-st** [comment]
Okay, thank you.
