### ISSUE TITLE
here call two times ZSTD_copy16 wont be bug?

### ISSUE THREAD

**Issue by sgf** [oleg-st/ZstdSharp#41]
in source of ZSTD_wildcopy  method,here call two times ZSTD_copy16(op, ip)wont be bug?

https://github.com/oleg-st/ZstdSharp/blob/b15b543ef7ea35b957f69af15988c4bfdad607d6/src/ZstdSharp/Unsafe/ZstdInternal.cs#L364

And the result of my test on Windows is: ZSTD_wildcopy seems to be slower than Unsafe.CopyBlockUnaligned.
In debug mode: I operated a 2488x2048 32-bit image. Each row of data was copied through memory.

ZSTD_wildcopy need 20ms
Unsafe.CopyBlockUnaligned need 4ms

**Comment by oleg-st** [comment]
2 calls ported from [here](https://github.com/facebook/zstd/blob/ad038d8768b36dc238d31dbf5f40c2a21339931a/lib/common/zstd_internal.h#L245). Also ZSTD_wildcopy takes into account possible buffer overlap.

**Comment by sgf** [comment]
It seems then that this function is not suitable for normal copying.
