### ISSUE TITLE
Question: Concatenating compressed data chunks

### ISSUE THREAD

**Issue by bill-poole** [oleg-st/ZstdSharp#44]
Is there a more efficient way to concatenate several chunks of compressed data into a single compressed chunk than decompressing and recompressing?

**Comment by oleg-st** [comment]
I think it's better to ask the authors of the [original library](https://github.com/facebook/zstd)

**Comment by oleg-st** [comment]
@bill-poole Could you forward your question to the [zstd](https://github.com/facebook/zstd/issues)?

**Comment by bill-poole** [comment]
Yes sorry, I got distracted with other things. See https://github.com/facebook/zstd/issues/4198.

**Comment by oleg-st** [comment]
code:

```csharp
var filenames = new[] { "file1", "file2" };

var combineMemoryStream = new MemoryStream();
var compressor = new Compressor();
foreach (var filename in filenames)
{
    var sourceBytes = File.ReadAllBytes(filename);
    var compressed = compressor.Wrap(sourceBytes);
    combineMemoryStream.Write(compressed);
    Console.WriteLine($"source {filename}, compressed {sourceBytes.Length} -> {compressed.Length}");
}

var decompressor = new Decompressor();
var combined = combineMemoryStream.ToArray();
var decompressed = decompressor.Unwrap(combined).ToArray();
Console.WriteLine($"combined, decompressed {combined.Length} -> {decompressed.Length}");
```

outputs:
```
source file1, compressed 478 -> 269
source file2, compressed 5706 -> 1930
combined, decompressed 2199 -> 6184
```

**Comment by bill-poole** [comment]
Oh wow, sorry, that's embarrassing. I must have had a bug in the testing code I did before I raised this issue. I've now confirmed with my own test that this works. Apologies for the inconvenience.
