### ISSUE TITLE
Since v0.7.6 DecompressionStream.Read(byte[],int,int) wont read all available bytes

### ISSUE THREAD

**Issue by jetelain** [oleg-st/ZstdSharp#47]
Hi,

Since version v0.7.6 reading a large chunk with `DecompressionStream.Read(byte[],int,int)` will not read all available bytes. It will only reads up to 256 KB. 

Steps to reproduce:
```
// Get file from https://cdn.dem.pmad.net/SRTM15Plus/SRTM15_N50_E000.ddc.zst
using var stream = File.OpenRead("SRTM15_N50_E000.ddc.zst");
using var compressed = new ZstdSharp.DecompressionStream(stream);

compressed.Read(new byte[0x38]); // Skip header
var dataSize = new BinaryReader(compressed).ReadInt32();
var bytes = new byte[dataSize];
var read = compressed.Read(bytes, 0, dataSize);
if (read != dataSize)
{
    Console.WriteLine($"FAILED: Read {read} on {dataSize}");
    // With ZstdSharp.Port 0.7.6: FAILED: Read 262084 on 3686400
}
else
{
    Console.WriteLine($"SUCCESS");
    // With ZstdSharp.Port 0.7.5: SUCCESS
}
```

Expected behavior:
Read the requested 3686400 bytes

Actual behavior:
Reads only 262084 bytes

**Comment by jetelain** [comment]
Likely introduced by #33

**Comment by oleg-st** [comment]
Hi, 
I think it is normal for `Stream.Read` to return less bytes than requested.

**Comment by jetelain** [comment]
Hi,

Yes, it's legit for Read, it's not forced to do so. But it's a behavior change that might break some implementations.

`ReadExactly` is designed to avoid that, but is "recent" (net7+) and legacy code base might assume that Read does read whole block.

**Comment by jetelain** [comment]
Ok, thank you for explanation
