### ISSUE TITLE
DecompressionStream should be safe to Dispose twice

### ISSUE THREAD

**Issue by avl** [oleg-st/ZstdSharp#8]
The DecompressionStream's Dispose-method calls ```ArrayPool<byte>.Shared.Return(this.inputBuffer);``` each time it is called.

According to the documentation for the IDisposable interface, "the object must ignore all calls after the first one".

As it is now, calling Dispose multiple times on DecompressionStream, corrupts the shared (global) ArrayPool.

The Dispose-method should be modified so that it does not return inputBuffer to the array pool more than once.

**Comment by oleg-st** [comment]
Thanks for reporting
I think it was introduced in #5

**Comment by oleg-st** [comment]
Fixed in #9
